package com.example.investfeed.domain

enum class ResponseCode(
    val code: String = "0000",
    val message: String
) {
    DASHBOARD(message = "대시보드 조회에 성공하셨습니다."),
    DASHBOARD_STREAM(message = "실시간 대시보드 조회에 성공하셨습니다."),
    ASSET_DASHBOARD(message = "통합 자산 대시보드 조회에 성공하셨습니다."),
    ASSET_STOCK_STREAM(message = "실시간 통합자산 주식 조회에 성공하셨습니다."),
    ASSET_CRYPTO_STREAM(message = "실시간 통합자산 코인 조회에 성공하셨습니다."),
    MULTI_VIEW_STOCK_STREAM(message = "실시간 멀티뷰 주식 조회에 성공하셨습니다."),
    MULTI_VIEW_CRYPTO_STREAM(message = "실시간 멀티뷰 코인 조회에 성공하셨습니다."),
    RANK_STREAM(message = "실시간 주식 순위 조회에 성공하셨습니다."),

    TIME_NOW(message = "현재 서버 시간 조회에 성공하셨습니다."),

    SECT_LIST(message = "전업종 지수 목록 조회에 성공하셨습니다."),
    SECT_LIST_STREAM(message = "실시간 전업종 지수 목록 조회에 성공하셨습니다."),
    SECT_STOCK_LIST(message = "업종별 주식 목록 조회에 성공하셨습니다."),

    RANK_LIST(message = "주식 순위 조회에 성공하셨습니다."),
    STOCK_DETAIL(message = "주식 상세 조회에 성공하셨습니다."),
    STOCK_DETAIL_WS(message = "실시간 주식 상세 조회에 성공하셨습니다."),
    STOCK_SEARCH(message = "종목 검색에 성공하셨습니다."),
    STOCK_PROGRAM_CHART(message = "종목 시간별 프로그램 매매 조회에 성공하셨습니다."),

    INVESTOR_LIST(message = "투자자별 목록 조회에 성공하셨습니다."),

    HOLDING_LIST(message = "보유 주식 조회에 성공하셨습니다."),
    HOLDING_STREAM(message = "실시간 보유 주식 조회에 성공하셨습니다."),

    BROKER_LIST(message = "증권사 목록 조회에 성공하셨습니다."),
    BROKER_CREATE(message = "증권사 등록에 성공하셨습니다."),
    BROKER_UPDATE(message = "증권사 수정에 성공하셨습니다."),
    BROKER_DELETE(message = "증권사 삭제에 성공하셨습니다."),

    MY_BROKER_LIST(message = "내 증권사 목록 조회에 성공하셨습니다."),
    MY_BROKER_ADD(message = "내 증권사 추가에 성공하셨습니다."),
    MY_BROKER_REMOVE(message = "내 증권사 삭제에 성공하셨습니다."),

    MANUAL_HOLDING_LIST(message = "수동 보유주식 조회에 성공하셨습니다."),
    MANUAL_HOLDING_CREATE(message = "수동 보유주식 등록에 성공하셨습니다."),
    MANUAL_HOLDING_UPDATE(message = "수동 보유주식 수정에 성공하셨습니다."),
    MANUAL_HOLDING_DELETE(message = "수동 보유주식 삭제에 성공하셨습니다."),
    HOLDING_REORDER(message = "보유주식 순서 변경에 성공하셨습니다."),
    MEMBER_BROKER_BALANCE_UPDATE(message = "계좌 잔액 수정에 성공하셨습니다."),

    INDEX_LIST(message = "지수 목록 조회에 성공하셨습니다."),
    INDEX_STREAM(message = "실시간 지수 조회에 성공하셨습니다."),
    INDEX_DETAIL(message = "지수 상세 조회에 성공하셨습니다."),

    COMMODITY_LIST(message = "원자재 목록 조회에 성공하셨습니다."),
    COMMODITY_STREAM(message = "실시간 원자재 조회에 성공하셨습니다."),
    COMMODITY_DETAIL(message = "원자재 상세 조회에 성공하셨습니다."),

    THEME_LIST(message = "테마 그룹별 조회에 성공하셨습니다."),
    THEME_STOCK_LIST(message = "테마 구성 종목 조회에 성공하셨습니다."),
    THEME_STOCK_LIST_STREAM(message = "실시간 테마 구성 종목 조회에 성공하셨습니다."),

    RECOMMEND_LIST(message = "주식 추천 목록 조회에 성공하셨습니다."),
    RECOMMEND_LIST_STREAM(message = "실시간 주식 추천 목록 조회에 성공하셨습니다."),
    RECOMMEND_SETTING(message = "추천 설정 조회에 성공하셨습니다."),
    RECOMMEND_SETTING_SAVE(message = "추천 설정 저장에 성공하셨습니다."),

    AUTH_UNAUTHORIZED(code = "AUTH_4001", message = "인증이 필요합니다."),
    AUTH_FORBIDDEN(code = "AUTH_4003", message = "접근 권한이 없습니다."),
    VALIDATION_FAILED(code = "VALIDATION_4001", message = "입력값 검증에 실패했습니다."),

    AUTH_REISSUE(message = "토큰 재발급에 성공하셨습니다."),
    AUTH_LOGOUT(message = "로그아웃에 성공하셨습니다."),
    AUTH_CHANGE_PASSWORD(message = "비밀번호 변경에 성공하셨습니다."),
    AUTH_LOCK(message = "계정 잠금에 성공하셨습니다."),
    AUTH_UNLOCK(message = "계정 잠금 해제에 성공하셨습니다."),
    AUTH_CHANGE_ROLE(message = "계정 권한 변경에 성공하셨습니다."),
    AUTH_CREATE_MEMBER(message = "회원 생성에 성공하셨습니다."),
    AUTH_MEMBER_LIST(message = "회원 목록 조회에 성공하셨습니다."),
    AUTH_ROLE_LIST(message = "역할 목록 조회에 성공하셨습니다."),
    AUTH_ROLE_CREATE(message = "역할 생성에 성공하셨습니다."),
    AUTH_ROLE_UPDATE(message = "역할 수정에 성공하셨습니다."),
    AUTH_ROLE_DELETE(message = "역할 삭제에 성공하셨습니다."),
    AUTH_ROLE_ORDER_UPDATE(message = "역할 순서 변경에 성공하셨습니다."),

    PERMISSION_LIST(message = "권한 목록 조회에 성공하셨습니다."),
    PERMISSION_CREATE(message = "권한 생성에 성공하셨습니다."),
    PERMISSION_UPDATE(message = "권한 수정에 성공하셨습니다."),
    PERMISSION_DELETE(message = "권한 삭제에 성공하셨습니다."),
    PERMISSION_PATTERN_ADD(message = "API 패턴 추가에 성공하셨습니다."),
    PERMISSION_PATTERN_DELETE(message = "API 패턴 삭제에 성공하셨습니다."),
    PERMISSION_ACTION_ADD(message = "지원 action 추가에 성공하셨습니다."),
    PERMISSION_ACTION_DELETE(message = "지원 action 삭제에 성공하셨습니다."),
    PERMISSION_ROLE_UPDATE(message = "역할별 권한 변경에 성공하셨습니다."),
    AUTH_PROFILE(message = "프로필 조회에 성공하셨습니다."),
    AUTH_PROFILE_UPDATE(message = "프로필 수정에 성공하셨습니다."),

    AUTH_TOTP_REQUIRED(message = "TOTP 인증이 필요합니다."),
    AUTH_TOTP_SETUP(message = "TOTP 설정 QR코드가 생성되었습니다."),
    AUTH_TOTP_VERIFY(message = "TOTP 인증에 성공하셨습니다."),
    AUTH_TOTP_RESET(message = "TOTP 초기화에 성공하셨습니다."),

    AUTH_SECONDARY_REQUIRED(code = "AUTH_4040", message = "2차 비밀번호 인증이 필요합니다."),
    AUTH_SECONDARY_NOT_SET(code = "AUTH_4041", message = "2차 비밀번호가 설정되지 않았습니다."),
    AUTH_SECONDARY_SETUP(message = "2차 비밀번호가 설정되었습니다."),
    AUTH_SECONDARY_CHANGE(message = "2차 비밀번호가 변경되었습니다."),
    AUTH_SECONDARY_LOCK_STATUS(message = "2차 비밀번호 잠금 상태를 조회하였습니다."),
    AUTH_SECONDARY_VERIFY(message = "2차 비밀번호 인증에 성공하셨습니다."),

    AUTH_API_KEY_LIST(message = "API Key 목록 조회에 성공하셨습니다."),
    AUTH_API_KEY_CREATE(message = "API Key 등록에 성공하셨습니다."),
    AUTH_API_KEY_DELETE(message = "API Key 삭제에 성공하셨습니다."),
    AUTH_API_KEY_UNLOCK(message = "API Key 등록 잠금 해제에 성공하셨습니다."),

    INTEREST_GROUP_LIST(message = "관심종목 그룹 목록 조회에 성공하셨습니다."),
    INTEREST_GROUP_CREATE(message = "관심종목 그룹 생성에 성공하셨습니다."),
    INTEREST_GROUP_UPDATE(message = "관심종목 그룹 수정에 성공하셨습니다."),
    INTEREST_GROUP_DELETE(message = "관심종목 그룹 삭제에 성공하셨습니다."),
    INTEREST_GROUP_REORDER(message = "관심종목 그룹 순서 변경에 성공하셨습니다."),
    INTEREST_ITEM_LIST(message = "관심종목 목록 조회에 성공하셨습니다."),
    INTEREST_ITEM_ADD(message = "관심종목 추가에 성공하셨습니다."),
    INTEREST_ITEM_DELETE(message = "관심종목 삭제에 성공하셨습니다."),
    INTEREST_ITEM_REORDER(message = "관심종목 순서 변경에 성공하셨습니다."),
    INTEREST_ITEM_STREAM(message = "실시간 관심종목 조회에 성공하셨습니다."),

    CRYPTO_HOLDING_LIST(message = "보유 코인 조회에 성공하셨습니다."),
    CRYPTO_HOLDING_STREAM(message = "실시간 보유 코인 조회에 성공하셨습니다."),
    CRYPTO_BROKER_LIST(message = "거래소 목록 조회에 성공하셨습니다."),
    CRYPTO_MY_BROKER_LIST(message = "내 거래소 목록 조회에 성공하셨습니다."),
    CRYPTO_MY_BROKER_ADD(message = "내 거래소 추가에 성공하셨습니다."),
    CRYPTO_MY_BROKER_REMOVE(message = "내 거래소 삭제에 성공하셨습니다."),
    CRYPTO_MANUAL_HOLDING_LIST(message = "수동 보유코인 조회에 성공하셨습니다."),
    CRYPTO_MANUAL_HOLDING_CREATE(message = "수동 보유코인 등록에 성공하셨습니다."),
    CRYPTO_MANUAL_HOLDING_UPDATE(message = "수동 보유코인 수정에 성공하셨습니다."),
    CRYPTO_MANUAL_HOLDING_DELETE(message = "수동 보유코인 삭제에 성공하셨습니다."),
    CRYPTO_HOLDING_REORDER(message = "보유코인 순서 변경에 성공하셨습니다."),
    CRYPTO_MEMBER_BROKER_BALANCE_UPDATE(message = "거래소 잔액 수정에 성공하셨습니다."),

    CRYPTO_LIST(message = "암호화폐 목록 조회에 성공하셨습니다."),
    CRYPTO_LIST_STREAM(message = "실시간 암호화폐 목록 조회에 성공하셨습니다."),
    CRYPTO_DETAIL(message = "암호화폐 상세 조회에 성공하셨습니다."),
    CRYPTO_SEARCH(message = "암호화폐 검색에 성공하셨습니다."),
    CRYPTO_RANK_LIST(message = "암호화폐 거래대금 순위 조회에 성공하셨습니다."),
    CRYPTO_RANK_STREAM(message = "실시간 암호화폐 거래대금 순위 조회에 성공하셨습니다."),

    MARKET_INDEX(message = "주요 지수 조회에 성공하셨습니다."),

    CRYPTO_INTEREST_GROUP_LIST(message = "암호화폐 관심종목 그룹 목록 조회에 성공하셨습니다."),
    CRYPTO_INTEREST_GROUP_CREATE(message = "암호화폐 관심종목 그룹 생성에 성공하셨습니다."),
    CRYPTO_INTEREST_GROUP_UPDATE(message = "암호화폐 관심종목 그룹 수정에 성공하셨습니다."),
    CRYPTO_INTEREST_GROUP_DELETE(message = "암호화폐 관심종목 그룹 삭제에 성공하셨습니다."),
    CRYPTO_INTEREST_GROUP_REORDER(message = "암호화폐 관심종목 그룹 순서 변경에 성공하셨습니다."),
    CRYPTO_INTEREST_ITEM_LIST(message = "암호화폐 관심종목 목록 조회에 성공하셨습니다."),
    CRYPTO_INTEREST_ITEM_ADD(message = "암호화폐 관심종목 추가에 성공하셨습니다."),
    CRYPTO_INTEREST_ITEM_DELETE(message = "암호화폐 관심종목 삭제에 성공하셨습니다."),
    CRYPTO_INTEREST_ITEM_REORDER(message = "암호화폐 관심종목 순서 변경에 성공하셨습니다."),
    CRYPTO_INTEREST_ITEM_STREAM(message = "실시간 암호화폐 관심종목 조회에 성공하셨습니다."),

    REALIZED_PNL_LIST(message = "실현손익 목록 조회에 성공하셨습니다."),
    REALIZED_PNL_SYNC(message = "실현손익 동기화에 성공하셨습니다."),
    REALIZED_PNL_MANUAL_CREATE(message = "수동 실현손익 등록에 성공하셨습니다."),
    REALIZED_PNL_MANUAL_UPDATE(message = "수동 실현손익 수정에 성공하셨습니다."),
    REALIZED_PNL_MANUAL_DELETE(message = "수동 실현손익 삭제에 성공하셨습니다."),

    NOTIFICATION_LIST(message = "알림 목록 조회에 성공하셨습니다."),
    NOTIFICATION_UNREAD_COUNT(message = "안읽은 알림 수 조회에 성공하셨습니다."),
    NOTIFICATION_READ(message = "알림 읽음 처리에 성공하셨습니다."),
    NOTIFICATION_READ_ALL(message = "전체 알림 읽음 처리에 성공하셨습니다."),

    NEWS_SEARCH(message = "뉴스 검색에 성공하셨습니다."),

    ECONOMIC_INDICATORS(message = "경제 지표 조회에 성공하셨습니다."),
    ECONOMIC_HISTORY(message = "경제 지표 추이 조회에 성공하셨습니다."),
    CALENDAR_EVENT_LIST(message = "일정 목록 조회에 성공하셨습니다."),
    CALENDAR_EVENT_CREATE(message = "일정 등록에 성공하셨습니다."),
    CALENDAR_EVENT_UPDATE(message = "일정 수정에 성공하셨습니다."),
    CALENDAR_EVENT_DELETE(message = "일정 삭제에 성공하셨습니다."),
    CALENDAR_REFRESH(message = "캘린더 데이터 갱신에 성공하셨습니다."),
    CALENDAR_BULK_REFRESH_START(message = "일괄 재생성을 시작했습니다."),
    CALENDAR_BULK_REFRESH_STATUS(message = "일괄 재생성 진행 상황을 조회하였습니다."),

    NOTIFICATION_SETTING(message = "알림 설정 조회에 성공하셨습니다."),
    NOTIFICATION_SETTING_SAVE(message = "알림 설정 저장에 성공하셨습니다."),

    PRICE_TARGET_CREATE(message = "목표가 알림 등록에 성공하셨습니다."),
    PRICE_TARGET_LIST(message = "목표가 알림 목록 조회에 성공하셨습니다."),
    PRICE_TARGET_DELETE(message = "목표가 알림 삭제에 성공하셨습니다."),

    REBALANCING_SETTING_SAVE(message = "리밸런싱 설정 저장에 성공하셨습니다."),
    REBALANCING_STATUS(message = "리밸런싱 현황 조회에 성공하셨습니다."),
    REBALANCING_SETTING_DELETE(message = "리밸런싱 설정 삭제에 성공하셨습니다."),

    GOAL_CREATE(message = "투자 목표 등록에 성공하셨습니다."),
    GOAL_UPDATE(message = "투자 목표 수정에 성공하셨습니다."),
    GOAL_DELETE(message = "투자 목표 삭제에 성공하셨습니다."),
    GOAL_LIST(message = "투자 목표 조회에 성공하셨습니다."),

    MENU_LIST(message = "메뉴 목록 조회에 성공하셨습니다."),
    MENU_MY_LIST(message = "사용자 메뉴 목록 조회에 성공하셨습니다."),
    MENU_CREATE(message = "메뉴 생성에 성공하셨습니다."),
    MENU_UPDATE(message = "메뉴 수정에 성공하셨습니다."),
    MENU_DELETE(message = "메뉴 삭제에 성공하셨습니다."),
    MENU_STRUCTURE_UPDATE(message = "메뉴 구조 변경에 성공하셨습니다."),
    MENU_BROKER_UPDATE(message = "메뉴 API Key 의존성 변경에 성공하셨습니다."),

    MONITORING_SCHEDULER_OVERVIEW(message = "스케줄러 모니터링 조회에 성공하셨습니다."),
    MONITORING_CONFIG_LOGS_OVERVIEW(message = "스케줄러 설정 변경 이력 조회에 성공하셨습니다."),
    MONITORING_REDIS_OVERVIEW(message = "Redis 캐시 현황 조회에 성공하셨습니다."),
    MONITORING_ERROR_LOGS_OVERVIEW(message = "에러 로그 조회에 성공하셨습니다."),
    MONITORING_API_CALLS_OVERVIEW(message = "외부 API 호출 통계 조회에 성공하셨습니다."),
    MONITORING_SYSTEM_OVERVIEW(message = "시스템 상태 조회에 성공하셨습니다."),

    MONITORING_SCHEDULER_TIMEOUT_UPDATE(message = "스케줄러 timeout 수정에 성공하셨습니다."),
    MONITORING_SCHEDULER_TRIGGER(message = "스케줄러 수동 실행을 요청했습니다."),
    MONITORING_SCHEDULER_LOG_ACKNOWLEDGE(message = "로그 확인 처리에 성공하셨습니다."),
    MONITORING_SCHEDULER_LOG_CANCEL_ACKNOWLEDGE(message = "로그 확인 취소에 성공하셨습니다."),
    MONITORING_ERROR_LOG_ACKNOWLEDGE(message = "에러 로그 확인 처리에 성공하셨습니다."),
    MONITORING_ERROR_LOG_CANCEL_ACKNOWLEDGE(message = "에러 로그 확인 취소에 성공하셨습니다."),
    MONITORING_BULK_ACKNOWLEDGE(message = "로그 일괄 확인 처리에 성공하셨습니다."),
    MONITORING_ACK_HISTORY(message = "확인 이력 조회에 성공하셨습니다."),
    MONITORING_REDIS_INVALIDATE(message = "Redis 캐시 무효화에 성공하셨습니다."),

}