spring:
  application:
    name: InvestFeed
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/investfeed
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: investfeed-secret-key-must-be-at-least-256-bits-long-for-hs256
  access-token-expiration: 1800000    # 30분 (ms)
  refresh-token-expiration: 604800000 # 7일 (ms)

kiwoom:
  app-key: ENoqH8oL9GF9Xt651kcNTfDpLXtTYwuGxjbvnOkCFWc
  secret-key: P3NIlTVvvicHXGcDumxMRCHO4skMCQjAjLMX8khoMJg
  default-url: https://api.kiwoom.com